### PR TITLE
add deploy preview note to readme

### PR DESCRIPTION
**Pull request by chrismclarke**
Testing PR preview feature

### CODE REVIEW

**Comment by darigovresearch** [comment]
This feature looks like it's working for us. Is there anything else that's left to do for the pull request to be merged?

**Comment by darigovresearch** [comment]
@chrismclarke & @jaklatt92 is there anything that this pull request needs to be merged?

**Comment by jaklatt92** [comment]
@darigovresearch looked good to me! merged. Thanks!

**Comment by darigovresearch** [comment]
@jaklatt92 you're very welcome, thanks for merging!

**Pull request merged**
