### PR TITLE
Update link colors on download&support pages plus underline on hover

### PR DESCRIPTION
**Pull request by martisj**
image

### CODE REVIEW

**Comment by davehakkens** [comment]
nice one. is it possible to keep the correct color in the menu on the left side?
And we could also do this for the create section.. also hard to see a url there with the yellow.

Or we just make all url's blue @saskiarysenbry?

**Comment by martisj** [comment]
> nice one. is it possible to keep the correct color in the menu on the left side?
> And we could also do this for the create section.. also hard to see a url there with the yellow.
> 
> Or we just make all url's blue @saskiarysenbry?

Sure, I can't remember what color it was in the nav menu, was it gray? All blue seems pretty straightforward as well. I like that the color of the links in the nav menu are the same as the links in the document 🤩

**Comment by davehakkens** [comment]
ok then let's keep the original color for the other sections! (inc create)
And blue url only for the intro, support and download.
But would be good to change the sidebar color from blue back to original grey
#e1e1e1

**Comment by martisj** [comment]
> ok then let's keep the original color for the other sections! (inc create)
> And blue url only for the intro, support and download.
> But would be good to change the sidebar color from blue back to original grey
> #e1e1e1

There we go @davehakkens I have changed the sidenav items back to grey and changed the link color to precious plastics blue for `download`, `support` & `create` pages.

**Pull request merged**
