### PR TITLE
License improvements

### LINKED ISSUE #117: Clarification on License
Is it possible to have a section called license in the readme that clarifies the licence of the project?

There is already a page but having it explicit will help people to know what they can and can't do with the project including contributing back to the project.

i.e.

## License
Different parts of this project are under different license conditions
Code license - GPL
Content license - Creative Commons Attribution - Sharealike International 4.0

### PR DESCRIPTION
**Pull request by darigovresearch**
Would resolve #117 if merged

### CODE REVIEW

**Comment by darigovresearch** [comment]
Is there anything else that is required for this pull request to be merged?

This pull request will now align it to the fixing fashion academy which was a pull request that was made & merged https://github.com/ONEARMY/fixing-fashion-academy/pull/6

Academy github page - https://github.com/ONEARMY/fixing-fashion-academy
Academy intro page - https://community.fixing.fashion/academy/start/intro.html

**Comment by darigovresearch** [comment]
@davehakkens is there anything else that is required for this pull request to be merged?

**Comment by darigovresearch** [comment]
@davehakkens thanks for the merge. I see that the changes are not yet reflected in the live site - https://community.preciousplastic.com/academy/intro.html

Is this because the continuous integration is broken or it is batch updated at the end of every week etc?

**Comment by davehakkens** [comment]
Hmm.. not sure.. Should be live after a merge..
We don't do batch updates or version releases for the academy.

Sounds like it might be a deeper problem

**Pull request merged**
