### PR TITLE
Change to GitHub releases for downloads

### PR DESCRIPTION
**Pull request by martisj**
BIG CAVEAT: there is a limit on how many requests to the GITHUB api we can do without logging in 😭 
So we might need a server that can cache the requests and authenticate.
A big one! 💥 

You can add a github release and display the stats where you want. In order to be flexible I had to make it a little more elaborate to use  🐢 

1. Add a link to the github release via the api: `https://api.github.com/repos/ONEARMY/precious-plastic-kit/releases/latest` <--- gets the latest kit from the GitHub api.
2. `<a href="https://api.github.com/repos/ONEARMY/precious-plastic-kit/releases/latest">Download</a>`
3. Give it a class of "js-getLinkDetails" and id. The `id` is used to decide where to display the file size, version and download count.
4. Add `<{whatever_tag} id="{id_from_above}-fileSize"></{whatever_tag}>`
5. full example:

```
<a class="downloadButton js-getLinkDetails" id="kit" href="https://api.github.com/repos/ONEARMY/precious-plastic-kit/releases/latest">Download</a>
stuff here and there
<p>things and more</p>
Now I want to show the download stats for the button above ☝️Here:
version: <span id="kit-version"></span>
downloads: <span id="kit-downloadCount"></span> NOTE: downloadCount gets the text "downloads" appended as a suffix.
file size: <span id="kit-fileSize"></span> NOTE: file size is written with 2 decimals and converted to MB, GB or KB depending on size.
```

Which produces:

[DOWNLOAD] button
...
...
...
version: V4.0.0
downloads: 420 downloads
file size: 1.49 GB

### CODE REVIEW

**Comment by chrismclarke** [comment]
As for the api limits, am I correct in thinking all the api requests come from the custom-js script? If so we could probably add an auth token to the request. I see the unauthenticated limit is 60 requests per hour which sounds fairly easily reached, I'd hope the authenticated 1500 should be sufficient enough but if not we could add a cache somewhere else

**Comment by chrismclarke** [comment]
Actually scratch part of that last comment. Yes the limit is 60 requests per hour but that's base on the IP address the request is coming from. So basically if somebody reloads the downloads page 60 times in a row they will hit that limit, but I don't think it's worth worrying about.

I looked into how easy it would be to include an auth token in the request however it's really not worth it. There's no way of adding encrypted variables to a docusaurus app and so we'd have to add a server endpoint for it somewhere else.

**Comment by chrismclarke** [comment]
Also @davehakkens  for reference, this is what the page looks like with the changes made by @martisj 

image

**Comment by martisj** [comment]
> I looked into how easy it would be to include an auth token in the request however it's really not worth it. There's no way of adding encrypted variables to a docusaurus app and so we'd have to add a server endpoint for it somewhere else.

Indeed. It seems overkill. If someone refreshes 10 times on the downloads page they will exceed it because we do one request for each download link. Anyhow; it's a problem when it becomes a problem  😃 

@chrismclarke thanks for the screenshot. As for rounding, I change to nearest MB now.

**Comment by davehakkens** [comment]
yeah look cool!
Could we also have 1 line underneath the main kit? example:
afbeelding

**Pull request merged**
