### PR TITLE
Make download button styles

### PR DESCRIPTION
**Pull request by martisj**
image

First draft at making a "vlc like"download button ref: 
Screen Shot 2019-11-17 at 21 00 15

### CODE REVIEW

**Comment by davehakkens** [comment]
Hi Martin

Nice button!
So we've been thinking quite a bit on this, and found a good way to track downloads using a URL tracker. Currently we download the repository directly as a .zip from Github.

- Github repository: https://github.com/ONEARMY/precious-plastic-kit
- Current URL for direct downloading (we stop using this): https://github.com/ONEARMY/precious-plastic-kit/archive/master.zip
- New URL we use for downloading https://cutt.ly/precious-plastic-kit

So we start tracking the downloads. But cutt.ly also actually has an API that you can use to show the amount of downloads. https://cutt.ly/cuttly-api 

> In the case of access to statistics, open the file https://cutt.ly/api/api.php remotely with the following parameter:

>$json = file_get_contents(https://cutt.ly/api/api.php?key=[API_KEY]&stats=[SHORTENED_URL]);
>`$data["stats"]["clicks"]` - total number of clicks

Not sure if this is above your coding skills, it also not a must. We could add it later. At least we are tracking! But just wanted to inform on the path forward for this.

**Comment by martisj** [comment]
@davehakkens regarding the download count, we can get the count from github releases (ref: https://help.github.com/en/github/administering-a-repository/getting-the-download-count-for-your-releases). So if you don't want to use the cutt.ly we don't have to. I am working on a new branch to solve this now.

**Comment by martisj** [comment]
I believe github is more reliable than cutt.ly for content delivery.

**Comment by davehakkens** [comment]
yeh looked into this for a while as well..
But the delivering in versions seemed a bit..weird. 
Mainly because it doesn't pull information form the master. But you need to manually upload a .zip in order for it to track downloads otherwise it doesn't work..
We did this before for V3 as well, here are [our releases ](https://github.com/ONEARMY/precious-plastic-kit/releases)But for some reason it didn't work properly. [No stats](https://somsubhra.com/github-release-stats/?username=onearmy&repository=precious-plastic-kit)

Maybe I just didin't get it.
But optionally we could always use the cutt.ly url to refer to the latest version using this URL
`https://github.com/ONEARMY/precious-plastic-kit/releases/latest/download/precious-plastic-kit.zip`

**Comment by martisj** [comment]
I am getting downloads for the latest release there:
Pasted_Image_05_01_2020__16_19

Are you expecting a higher  number?

This is what I've got now:
image

The number (6) is pulled from the latest release of ONEARMY/precious-plastic-kit https://api.github.com/repos/ONEARMY/precious-plastic-kit/releases/latest

**Pull request merged**
